version: '2.2'
services:
  logstash:
    build:
      context: "${PWD}/"
      dockerfile: logstash.Dockerfile
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    volumes:
      - ./pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./multiple-input.conf/:/usr/share/logstash/pipeline/logstash-local.conf

networks:
  default:
    external:
      name: elastic
